<Project Sdk="Aspire.AppHost.Sdk/13.0.0">

  <ItemGroup>
    <ProjectReference Include="..\10-DemoServer\DemoServer.csproj" />
    <ProjectReference Include="..\20-McpStreamableServer\McpStreamableServer.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>bfbcdbb1-4b0d-4bfc-bf80-6f5afa86323d</UserSecretsId>
  </PropertyGroup>

</Project>
